Repository h2oai/wave, pull requests merged in 2021-01, with the labels that each got.

#448 Github actions pipeline to cut a release in Wave
  .github/workflows/release.yml
  Makefile
  py/Makefile
  py/setup.py
Labels: packaging, test

#485 Remove old mentions of 'Q' in scripts.md
  website/docs/scripts.md
Labels: docs

#463 Publish Wave to Conda
  .github/workflows/release.yml
  py/README.md
  py/conda/conda_build_config.yaml
  py/conda/meta.yaml
  py/setup.py
  website/docs/tutorial-hello.md
Labels: packaging

#491 fix: explicitly set conda package name
  py/conda/meta.yaml
Labels: packaging
